/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "@aws-amplify/ui-react/internal";
import { Text, View } from "@aws-amplify/ui-react";
export default function AndroidSmall3(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="366px"
      height="704px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      overflow="hidden"
      position="relative"
      padding="0px 0px 0px 0px"
      backgroundColor="rgba(204,236,243,1)"
      {...getOverrideProps(overrides, "AndroidSmall3")}
      {...rest}
    >
      <View
        width="320px"
        height="263px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        overflow="hidden"
        position="absolute"
        top="63px"
        left="21px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(255,255,255,1)"
        {...getOverrideProps(overrides, "Frame 13")}
      >
        <Text
          fontFamily="K2D"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="130px"
          height="36px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="21px"
          left="17px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="総販"
          {...getOverrideProps(overrides, "\u7DCF\u8CA914268")}
        ></Text>
        <Text
          fontFamily="K2D"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="58px"
          height="33px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="23px"
          left="195px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="台"
          {...getOverrideProps(overrides, "\u53F0")}
        ></Text>
        <Text
          fontFamily="K2D"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="130px"
          height="33px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="77px"
          left="17px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="MNP比率"
          {...getOverrideProps(overrides, "MNP\u6BD4\u7387")}
        ></Text>
        <Text
          fontFamily="K2D"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="58px"
          height="33px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="77px"
          left="195px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="％"
          {...getOverrideProps(overrides, "\uFF0514271")}
        ></Text>
        <Text
          fontFamily="K2D"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="130px"
          height="33px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="143px"
          left="17px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="auPAYカード"
          {...getOverrideProps(overrides, "auPAY\u30AB\u30FC\u30C914272")}
        ></Text>
        <Text
          fontFamily="K2D"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="58px"
          height="33px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="138px"
          left="195px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="件"
          {...getOverrideProps(overrides, "\u4EF614273")}
        ></Text>
        <Text
          fontFamily="K2D"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="83px"
          height="33px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="201px"
          left="40px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="ひかり"
          {...getOverrideProps(overrides, "\u3072\u304B\u308A14274")}
        ></Text>
        <Text
          fontFamily="K2D"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="58px"
          height="33px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="201px"
          left="195px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="件"
          {...getOverrideProps(overrides, "\u4EF614275")}
        ></Text>
        <View
          width="53px"
          height="26px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="25px"
          left="146px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(217,217,217,1)"
          {...getOverrideProps(overrides, "Rectangle 4")}
        ></View>
        <View
          width="53px"
          height="26px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="81px"
          left="146px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(217,217,217,1)"
          {...getOverrideProps(overrides, "Rectangle 5")}
        ></View>
        <View
          width="53px"
          height="26px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="142px"
          left="146px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(217,217,217,1)"
          {...getOverrideProps(overrides, "Rectangle 6")}
        ></View>
        <View
          width="53px"
          height="26px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="206px"
          left="147px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(217,217,217,1)"
          {...getOverrideProps(overrides, "Rectangle 714279")}
        ></View>
      </View>
      <View
        width="320px"
        height="306px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        overflow="hidden"
        position="absolute"
        top="337px"
        left="20px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(255,255,255,1)"
        {...getOverrideProps(overrides, "Frame 14")}
      >
        <Text
          fontFamily="K2D"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="130px"
          height="36px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="58px"
          left="0px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="総販"
          {...getOverrideProps(overrides, "\u7DCF\u8CA914281")}
        ></Text>
        <Text
          fontFamily="K2D"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="58px"
          height="33px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="58px"
          left="131px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="％"
          {...getOverrideProps(overrides, "\uFF0514282")}
        ></Text>
        <Text
          fontFamily="K2D"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="130px"
          height="33px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="176px"
          left="17px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="auPAYカード"
          {...getOverrideProps(overrides, "auPAY\u30AB\u30FC\u30C914283")}
        ></Text>
        <Text
          fontFamily="K2D"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="58px"
          height="33px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="180px"
          left="189px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="％"
          {...getOverrideProps(overrides, "\uFF0514284")}
        ></Text>
        <Text
          fontFamily="K2D"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="245px"
          height="44px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="8px"
          left="37px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="個人予算達成率"
          {...getOverrideProps(
            overrides,
            "\u500B\u4EBA\u4E88\u7B97\u9054\u6210\u7387"
          )}
        ></Text>
        <Text
          fontFamily="K2D"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="130px"
          height="33px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="110px"
          left="1px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="ひかり"
          {...getOverrideProps(overrides, "\u3072\u304B\u308A14286")}
        ></Text>
        <Text
          fontFamily="K2D"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26px"
          textAlign="center"
          display="block"
          direction="column"
          justifyContent="unset"
          width="58px"
          height="33px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="110px"
          left="130px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="％"
          {...getOverrideProps(overrides, "\uFF0514287")}
        ></Text>
        <View
          width="53px"
          height="26px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="58px"
          left="94px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(217,217,217,1)"
          {...getOverrideProps(overrides, "Rectangle 714288")}
        ></View>
        <View
          width="53px"
          height="26px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="114px"
          left="94px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(217,217,217,1)"
          {...getOverrideProps(overrides, "Rectangle 8")}
        ></View>
        <View
          width="53px"
          height="26px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="180px"
          left="147px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(217,217,217,1)"
          {...getOverrideProps(overrides, "Rectangle 9")}
        ></View>
      </View>
      <Text
        fontFamily="K2D"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="26px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="23px"
        left="161px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="月実績"
        {...getOverrideProps(overrides, "\u6708\u5B9F\u7E3E")}
      ></Text>
      <View
        width="63px"
        height="38px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="17px"
        left="88px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(217,217,217,1)"
        {...getOverrideProps(overrides, "Rectangle 11")}
      ></View>
    </View>
  );
}
